### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by zek** [ibuclaw/gccjitd#1]
Building gccjitd ~master configuration "library", build type debug.
Running dmd...
....\AppData\Roaming\dub\packages\gccjitd-master\gccjit\c.d(259): Error: functi
on gccjit.c.gcc_jit_context_get_first_error without 'this' cannot be const
....\AppData\Roaming\dub\packages\gccjitd-master\gccjit\c.d(305): Error: functi
on gccjit.c.gcc_jit_object_get_debug_string without 'this' cannot be const
FAIL ....\AppData\Roaming\dub\packages\gccjitd-master.dub\build\library-debug-
windows-x86-dmd_2066-2AB6F6B9D5815F05FA2AD4D1F0418EAA\ gccjitd staticLibrary
Error executing command run: dmd failed with exit code 1.

**Comment by ibuclaw** [comment]
https://github.com/ibuclaw/gccjitd/commit/b897a4fd668783408c65637afa5cc67e13d0e645

I'll update tags too, as I fixed this before switching to dub (as shown in commit timestamps).

**Comment by zek** [comment]
I am on windows. Where to find gccjit.lib file?

**Comment by davidmalcolm** [comment]
FWIW I've not attempted to build libgccjit on Windows.  I'm interested in hearing how you get on with it.  Does libgccjit itself work there? (i.e. without the D bindings?)

**Comment by davidmalcolm** [comment]
I have a feeling I may e.g. have used forward slash for directory separators in various places in libgccjit, which I suspect may cause issues.  (though, if so, this kind of thing is better dealt with in the upstream libgccjit bug tracker; https://gcc.gnu.org/bugzilla)

**Comment by ibuclaw** [comment]
@davidmalcolm - I echo that feeling too.  Though perhaps most people on Windows would be using Cygwin as opposed to MinGW.

**Comment by zek** [comment]
Actually I just need a JIT library that works at linux and windows. 
I thought i can use gccjitd.

**Comment by davidmalcolm** [comment]
On Mon, 2015-01-26 at 13:18 -0800, Talha Zekeriya Durmuş wrote:

> Actually I just need a JIT library that works at linux and windows. 
> I thought i can use gccjitd.
> As I understand it, gccjitd is a thin wrapper around libgccjit, so you
> need to build libgccjit before gccjitd is usable.  I don't know to what
> extent gccjitd automates the building and installation of libgccjit, but
> my guess is that it assumes that you've already done that.

As far as I know, no-one has yet attempted to build libgccjit on
Windows.  This could be interpreted as a challenge, if you're feeling
like being a pioneer (this is euphemistic way of saying, I'd be
surprised if it works first time, without a little patching :) )

Hope this is helpful
Dave

**Comment by zek** [comment]
Thank you for reply. To automate is not so important. I can call C functions directly. 

I have failed to build it.
For now I have postponed this. I have some other things to do.
But if any progress happens, I will say it.
